# Generated by Django 4.1.7 on 2023-03-24 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TODO', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Состояние'),
        ),
    ]
